scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
    focus_fit_method = 0 # center
    follow_focus = true
    follow_min_visible = 1.0 # this is disable auto focus on hover
    explicit_column_widths = 0.5, 0.667, 0.95
    direction = right
}

bind = Ctrl+Super, S, exec, ~/.config/hypr/hyprland/scripts/toggle_layout.sh
bind = Super, mouse:274, exec, ~/.config/hypr/hyprland/scripts/toggle_layout.sh

bind = Super+Ctrl, left,  layoutmsg, focus l
bind = Super+Ctrl, right, layoutmsg, focus r

bind = Super+Alt, mouse_down, layoutmsg, focus l
bind = Super+Alt, mouse_up, layoutmsg, focus r

bind = Super, Grave, layoutmsg, promote
